version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: online_election_system
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - election-network

  election:
    build: .
    container_name: election
    restart: always
    command: ["python", "manage.py", "runserver", "0.0.0.0:8002"]
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - mysql
    environment:
      - DATABASE_NAME=online_election_system
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
    networks:
      - election-network

volumes:
  mysql_data:

networks:
  election-network:
