# Generated by Django 5.0.3 on 2024-03-20 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_candidate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elections.candidate'),
            preserve_default=False,
        ),
    ]
